# Cloudflare Pages configuration for Frame Foundry
name = "framefoundry"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[build]
command = "npm run build"
cwd = ""

[env.production]
NODE_VERSION = "18"